import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Branding & Navigation
    logo: "AIRA",
    tagline: "Radiology AI Screening",
    navHome: "Home",
    navDashboard: "Dashboard",
    navHistory: "History",
    navScanner: "Radiology Analysis",
    navResults: "Analysis Results",
    navReports: "Reports & History",
    navModelPerformance: "Model Analytics",
    navDoctors: "Doctors",
    navInvitations: "Invitations",
    navBilling: "Billing & Subscription",
    navAuditLogs: "Audit Logs",
    navRequests: "Approval Requests",
    navSettings: "Settings",
    logout: "Log Out",
    welcome: "Welcome",
    
    // Auth & Onboarding
    loginTitle: "AIRA Screening Platform",
    loginSubtitle: "Secure Clinical Access Portal",
    email: "Email Address",
    password: "Password",
    firstName: "First Name",
    lastName: "Last Name",
    loginBtn: "Login",
    signingIn: "Signing in...",
    registerInstTitle: "Register Institution",
    registerInstSubtitle: "Apply for clinical access to AIRA platform",
    registerDocTitle: "Doctor Registration",
    registerDocSubtitle: "Create your practitioner account using invitation code",
    invitationCode: "Invitation Code",
    submitApplication: "Submit Application",
    registerBtn: "Register Account",
    instName: "Institution Name",
    instType: "Institution Type",
    publicHospital: "Public Hospital (CHU)",
    privateClinic: "Private Clinic",
    country: "Country",
    city: "City",
    address: "Physical Address",
    regNumber: "Registration / License Number",
    contactEmail: "Contact Email",
    contactPhone: "Contact Phone",
    respPerson: "Responsible Person (Admin)",
    needAccount: "Need to register?",
    registerInstLink: "Register your medical institution",
    haveCode: "Have an invitation code?",
    registerDocLink: "Register as a doctor",
    haveAccount: "Already registered? Login",
    
    // General
    loading: "Loading...",
    success: "Success",
    error: "Error",
    save: "Save Changes",
    status: "Status",
    actions: "Actions",
    date: "Date",
    view: "View",
    copy: "Copy",
    copied: "Copied!",
    
    // Doctor Workstation
    scannerTitle: "AI Radiology Scan Scanner",
    scannerSubtitle: "Upload a radiology scan for high-precision neural analysis",
    chooseImage: "Choose Radiology Scan",
    changeImage: "Change Image",
    runAnalysis: "Run AI Analysis",
    analyzing: "AI Analyzing Pipeline...",
    original: "Original",
    aiPrediction: "AI Prediction",
    overlay: "Overlay Map",
    segmentationMask: "Segmentation Mask",
    clinicalFindings: "AI Clinical Findings",
    stage1Classifier: "Stage 1 (Binary Classification)",
    stage2Classifier: "Stage 2 (Pathological Classification)",
    normal: "Normal Scan",
    abnormal: "Abnormal Scan",
    benign: "Benign Tumor",
    malignant: "Malignant Tumor",
    downloadReport: "Download Medical Report",
    disclaimer: "⚠️ CLINICAL DISCLAIMER: This neural diagnostic system is designed to assist licensed medical practitioners. It does not constitute a standalone medical diagnosis.",
    patientDetails: "Patient Details",
    patientIdField: "Patient ID",
    ageField: "Age",
    dateField: "Examination Date",
    analysisParameters: "Analysis Parameters",
    highSensitivityMode: "High-sensitivity Mode",
    highSensitivityDesc: "Enhanced detection for microcalcifications",
    highSensitivityWarning: "High-sensitivity mode may increase false-positive detection; radiologist verification required.",
    scanPreview: "Selected Scan Preview",
    scanPreviewPlaceholder: "Real-time scan preview will appear here",
    dragDropTitle: "Drag and drop mammogram images here",
    dragDropSubtitle: "Supports DICOM, high-res JPEG, or PNG formats",
    browseFiles: "Browse Local Files",
    historyTitle: "Scan Diagnosis History",
    noHistory: "No scans performed yet.",
    
    // Institution Admin Dashboard
    instAdminDashboard: "Institution Administration",
    generateCode: "Generate Invitation Code",
    expiresInDays: "Code Expiry (Days)",
    activeInvitations: "Active Doctor Invitations",
    codeColumn: "Invitation Code",
    expiryColumn: "Expires At",
    usedColumn: "Used Status",
    revokedColumn: "Revoked",
    revokeBtn: "Revoke",
    used: "Used",
    unused: "Unused",
    revoked: "Revoked",
    trialDaysRemaining: "Trial Days Remaining",
    currentPlan: "Current Subscription Plan",
    billingHistory: "Billing History",
    upgradePlan: "Upgrade Subscription Plan",
    monthlyPlan: "Monthly Billing ($49/mo)",
    yearlyPlan: "Yearly Billing ($499/yr)",
    payWithStripe: "Pay with Stripe",
    payWithPayPal: "Pay with PayPal",
    upgradeSuccess: "Subscription upgraded successfully!",
    totalDoctors: "Total Onboarded Doctors",
    totalScans: "Total Analyses Performed",
    
    // Super Admin Dashboard
    superAdminDashboard: "Platform Super Admin Dashboard",
    pendingRequests: "Pending Institution Applications",
    allInstitutions: "Registered Medical Institutions",
    approveBtn: "Approve",
    rejectBtn: "Reject",
    suspendBtn: "Suspend",
    unsuspendBtn: "Reactivate",
    totalInstitutions: "Total Institutions",
    activeInstitutions: "Active Facilities",
    pendingInstitutions: "Pending Approval",
    suspendedInstitutions: "Suspended Facilities",
    platformAnalytics: "System Analytics",
    monthlyRevenue: "Est. Monthly Revenue",
    recentSystemLogs: "Recent Audit Logs",
    systemLogsTitle: "Full Audit Trail Log",
    searchLogs: "Search audit trails...",
    userEmailCol: "User Email",
    actionCol: "Action performed",
    detailsCol: "Context details",
    ipCol: "Client IP"
  },
  ar: {
    // Branding & Navigation
    logo: "آيرا (AIRA)",
    tagline: "فحص الأشعة بالذكاء الاصطناعي",
    navHome: "الرئيسية",
    navDashboard: "لوحة التحكم",
    navHistory: "السجل والتقارير",
    navScanner: "تحليل الأشعة",
    navResults: "نتائج التحليل",
    navReports: "التقارير والسجل",
    navModelPerformance: "أداء نموذج AI",
    navDoctors: "الأطباء",
    navInvitations: "الدعوات",
    navBilling: "الاشتراكات والفوترة",
    navAuditLogs: "سجلات الأمان",
    navRequests: "طلبات المراجعة والاعتماد",
    navSettings: "الإعدادات",
    logout: "تسجيل الخروج",
    welcome: "مرحباً بك",
    
    // Auth & Onboarding
    loginTitle: "منصة آيرا الطبية",
    loginSubtitle: "بوابة الوصول السريري الآمن",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    loginBtn: "تسجيل الدخول",
    signingIn: "جاري تسجيل الدخول...",
    registerInstTitle: "تسجيل منشأة طبية جديدة",
    registerInstSubtitle: "تقديم طلب انضمام منشأتك إلى منصة آيرا",
    registerDocTitle: "تسجيل طبيب جديد",
    registerDocSubtitle: "إنشاء حساب ممارس طبي باستخدام رمز الدعوة",
    invitationCode: "رمز الدعوة (Invitation Code)",
    submitApplication: "إرسال الطلب للاعتماد",
    registerBtn: "إنشاء الحساب",
    instName: "اسم المنشأة / المستشفى",
    instType: "نوع المنشأة",
    publicHospital: "مستشفى حكومي (CHU)",
    privateClinic: "عيادة خاصة / مستشفى خاص",
    country: "الدولة",
    city: "المدينة",
    address: "العنوان بالكامل",
    regNumber: "رقم الترخيص / السجل التجاري",
    contactEmail: "بريد التواصل الإلكتروني",
    contactPhone: "رقم هاتف التواصل",
    respPerson: "الشخص المسؤول (المدير الإداري)",
    needAccount: "ليست لديك منشأة مسجلة؟",
    registerInstLink: "سجل منشأتك الطبية الآن",
    haveCode: "لديك رمز دعوة طبيب؟",
    registerDocLink: "سجل حسابك كطبيب",
    haveAccount: "مسجل بالفعل؟ تسجيل الدخول",
    
    // General
    loading: "جاري التحميل...",
    success: "تم بنجاح",
    error: "خطأ",
    save: "حفظ التغييرات",
    status: "الحالة",
    actions: "الإجراءات",
    date: "التاريخ",
    view: "عرض",
    copy: "نسخ",
    copied: "تم النسخ!",
    
    // Doctor Workstation
    scannerTitle: "فحص الأشعة بالذكاء الاصطناعي (AI)",
    scannerSubtitle: "قم برفع صورة الأشعة لإجراء تحليل عصبي متقدم فائق الدقة",
    chooseImage: "اختر صورة الأشعة",
    changeImage: "تغيير الصورة",
    runAnalysis: "تشغيل تحليل الذكاء الاصطناعي",
    analyzing: "جاري تشغيل خط المعالجة الذكي...",
    original: "الصورة الأصلية",
    aiPrediction: "توقع النظام",
    overlay: "تطابق الطبقات",
    segmentationMask: "قناع تحديد الورم (Segmentation)",
    clinicalFindings: "النتائج السريرية للذكاء الاصطناعي",
    stage1Classifier: "المرحلة الأولى (التصنيف الثنائي)",
    stage2Classifier: "المرحلة الثانية (التصنيف الباثولوجي)",
    normal: "فحص طبيعي (Normal)",
    abnormal: "فحص غير طبيعي (Abnormal)",
    benign: "حميد (Benign)",
    malignant: "خبيث (Malignant)",
    downloadReport: "تحميل التقرير الطبي المعتمد",
    disclaimer: "⚠️ إخلاء مسؤولية سريرية: هذا النظام المعتمد على الشبكات العصبية هو أداة مساعدة للطبيب المعالج، ولا يغني بأي شكل عن التقييم والتشخيص الطبي المتخصص.",
    patientDetails: "تفاصيل المريض",
    patientIdField: "معرف المريض",
    ageField: "العمر",
    dateField: "تاريخ الفحص",
    analysisParameters: "محددات التحليل",
    highSensitivityMode: "وضع الحساسية العالية",
    highSensitivityDesc: "تحسين اكتشاف التكلسات الدقيقة",
    highSensitivityWarning: "قد يزيد وضع الحساسية العالية من النتائج الإيجابية الكاذبة؛ مطلوب تحقق طبيب الأشعة.",
    scanPreview: "معاينة الأشعة المحددة",
    scanPreviewPlaceholder: "ستظهر معاينة الأشعة المباشرة هنا",
    dragDropTitle: "اسحب وأسقط صور الأشعة هنا",
    dragDropSubtitle: "يدعم صيغ DICOM أو JPEG عالية الدقة أو PNG",
    browseFiles: "تصفح الملفات المحلية",
    historyTitle: "سجل الفحوصات والتشخيصات",
    noHistory: "لا توجد فحوصات سابقة مسجلة.",
    
    // Institution Admin Dashboard
    instAdminDashboard: "الإدارة الإدارية للمنشأة",
    generateCode: "توليد رمز دعوة للأطباء",
    expiresInDays: "صلاحية الرمز (بالأيام)",
    activeInvitations: "رموز الدعوة النشطة للأطباء",
    codeColumn: "رمز الدعوة",
    expiryColumn: "تاريخ الانتهاء",
    usedColumn: "حالة الاستخدام",
    revokedColumn: "ملغي",
    revokeBtn: "إلغاء الصلاحية",
    used: "مستخدم",
    unused: "نشط وغير مستخدم",
    revoked: "ملغي",
    trialDaysRemaining: "الأيام المتبقية للفترة التجريبية",
    currentPlan: "باقة الاشتراك الحالية",
    billingHistory: "سجل عمليات الدفع والفوترة",
    upgradePlan: "ترقية باقة الاشتراك",
    monthlyPlan: "الاشتراك الشهري ($49/شهرياً)",
    yearlyPlan: "الاشتراك السنوي ($499/سنوياً)",
    payWithStripe: "الدفع بواسطة Stripe",
    payWithPayPal: "الدفع بواسطة PayPal",
    upgradeSuccess: "تم ترقية الاشتراك بنجاح!",
    totalDoctors: "عدد الأطباء المسجلين",
    totalScans: "إجمالي الفحوصات المجراة",
    
    // Super Admin Dashboard
    superAdminDashboard: "لوحة تحكم المشرف العام للمنصة",
    pendingRequests: "طلبات اعتماد المنشآت الطبية المعلقة",
    allInstitutions: "المنشآت الطبية المسجلة بالمنصة",
    approveBtn: "اعتماد وقبول",
    rejectBtn: "رفض الطلب",
    suspendBtn: "تعليق الحساب",
    unsuspendBtn: "إعادة تفعيل",
    totalInstitutions: "إجمالي المنشآت",
    activeInstitutions: "المنشآت النشطة",
    pendingInstitutions: "طلبات قيد المراجعة",
    suspendedInstitutions: "المنشآت المعلقة",
    platformAnalytics: "إحصائيات المنصة العامة",
    monthlyRevenue: "الإيرادات الشهرية التقديرية",
    recentSystemLogs: "سجل الأحداث والعمليات الأخير",
    systemLogsTitle: "سجل تتبع أمان عمليات النظام بالكامل",
    searchLogs: "البحث في السجلات الأمني...",
    userEmailCol: "البريد الإلكتروني",
    actionCol: "العملية المنفذة",
    detailsCol: "تفاصيل السياق",
    ipCol: "عنوان الـ IP للمستخدم"
  },
  fr: {
    // Branding & Navigation
    logo: "AIRA",
    tagline: "Dépistage par Intelligence Artificielle",
    navHome: "Accueil",
    navDashboard: "Tableau de Bord",
    navHistory: "Historique",
    navScanner: "Analyse d'Images",
    navResults: "Résultats d'Analyse",
    navReports: "Rapports & Historique",
    navModelPerformance: "Analyses du Modèle",
    navDoctors: "Médecins",
    navInvitations: "Invitations",
    navBilling: "Facturation & Abonnement",
    navAuditLogs: "Journaux d'Audit",
    navRequests: "Demandes d'Approbation",
    navSettings: "Paramètres",
    logout: "Se Déconnecter",
    welcome: "Bienvenue",
    
    // Auth & Onboarding
    loginTitle: "Plateforme Clinique AIRA",
    loginSubtitle: "Portail d'Accès Clinique Sécurisé",
    email: "Adresse Email",
    password: "Mot de Passe",
    firstName: "Prénom",
    lastName: "Nom",
    loginBtn: "Se Connecter",
    signingIn: "Connexion en cours...",
    registerInstTitle: "Enregistrer l'Institution",
    registerInstSubtitle: "Demander l'accès clinique à la plateforme AIRA",
    registerDocTitle: "Inscription du Médecin",
    registerDocSubtitle: "Créez votre compte praticien avec un code d'invitation",
    invitationCode: "Code d'Invitation",
    submitApplication: "Soumettre la Demande",
    registerBtn: "Créer le Compte",
    instName: "Nom de l'Institution",
    instType: "Type d'Institution",
    publicHospital: "Hôpital Public (CHU)",
    privateClinic: "Clinique Privée",
    country: "Pays",
    city: "Ville",
    address: "Adresse Physique",
    regNumber: "Numéro d'Enregistrement / Licence",
    contactEmail: "Email de Contact",
    contactPhone: "Téléphone de Contact",
    respPerson: "Personne Responsable (Admin)",
    needAccount: "Pas encore inscrit?",
    registerInstLink: "Enregistrer votre institution médicale",
    haveCode: "Vous avez un code d'invitation?",
    registerDocLink: "S'inscrire en tant que médecin",
    haveAccount: "Déjà inscrit? Se connecter",
    
    // General
    loading: "Chargement...",
    success: "Succès",
    error: "Erreur",
    save: "Enregistrer les modifications",
    status: "Statut",
    actions: "Actions",
    date: "Date",
    view: "Voir",
    copy: "Copier",
    copied: "Copié!",
    
    // Doctor Workstation
    scannerTitle: "Scanner Intelligent par IA",
    scannerSubtitle: "Téléchargez une image pour un diagnostic de haute précision",
    chooseImage: "Choisir l'image de radiographie",
    changeImage: "Modifier l'image",
    runAnalysis: "Lancer l'Analyse IA",
    analyzing: "Analyse Neuronale en cours...",
    original: "Original",
    aiPrediction: "Prédiction IA",
    overlay: "Superposition",
    segmentationMask: "Masque de Segmentation",
    clinicalFindings: "Conclusions Cliniques de l'IA",
    stage1Classifier: "Étape 1 (Classification Binaire)",
    stage2Classifier: "Étape 2 (Classification Pathologique)",
    normal: "Échographie Normale",
    abnormal: "Échographie Anormale",
    benign: "Tumeur Bénigne",
    malignant: "Tumeur Maligne",
    downloadReport: "Télécharger le Rapport Médical",
    disclaimer: "⚠️ AVERTISSEMENT CLINIQUE: Ce système de diagnostic assisté par IA est destiné à soutenir les médecins agréés. Il ne remplace pas le jugement clinique autonome.",
    patientDetails: "Détails du Patient",
    patientIdField: "ID du Patient",
    ageField: "Âge",
    dateField: "Date de l'examen",
    analysisParameters: "Paramètres d'Analyse",
    highSensitivityMode: "Mode Haute Sensibilité",
    highSensitivityDesc: "Détection améliorée des microcalcifications",
    highSensitivityWarning: "Le mode haute sensibilité peut augmenter la détection de faux positifs; vérification par radiologue requise.",
    scanPreview: "Aperçu de l'image sélectionnée",
    scanPreviewPlaceholder: "L'aperçu de l'image apparaîtra ici",
    dragDropTitle: "Glissez-déposez les images de mammographie ici",
    dragDropSubtitle: "Prend en charge les formats DICOM, JPEG haute résolution ou PNG",
    browseFiles: "Parcourir les fichiers",
    historyTitle: "Historique des Analyses",
    noHistory: "Aucune analyse effectuée pour le moment.",
    
    // Institution Admin Dashboard
    instAdminDashboard: "Administration de l'Établissement",
    generateCode: "Générer un Code d'Invitation",
    expiresInDays: "Expiration du Code (Jours)",
    activeInvitations: "Codes d'Invitation Actifs",
    codeColumn: "Code d'Invitation",
    expiryColumn: "Date d'Expiration",
    usedColumn: "Statut d'Utilisation",
    revokedColumn: "Révoqué",
    revokeBtn: "Révoquer",
    used: "Utilisé",
    unused: "Inutilisé",
    revoked: "Révoqué",
    trialDaysRemaining: "Jours d'essai restants",
    currentPlan: "Formule d'Abonnement Actuelle",
    billingHistory: "Historique des Transactions",
    upgradePlan: "Changer de Formule d'Abonnement",
    monthlyPlan: "Facturation Mensuelle ($49/mois)",
    yearlyPlan: "Facturation Annuelle ($499/an)",
    payWithStripe: "Payer avec Stripe",
    payWithPayPal: "Payer avec PayPal",
    upgradeSuccess: "Abonnement mis à jour avec succès!",
    totalDoctors: "Total Médecins Inscrit",
    totalScans: "Total Analyses Effectuées",
    
    // Super Admin Dashboard
    superAdminDashboard: "Portail d'Administration Global",
    pendingRequests: "Demandes d'Adhésion en Attente",
    allInstitutions: "Établissements Médicaux Enregistrés",
    approveBtn: "Approuver",
    rejectBtn: "Rejeter",
    suspendBtn: "Suspendre",
    unsuspendBtn: "Réactiver",
    totalInstitutions: "Total Institutions",
    activeInstitutions: "Établissements Actifs",
    pendingInstitutions: "En Attente de Revue",
    suspendedInstitutions: "Établissements Suspendus",
    platformAnalytics: "Analyses de Performance globale",
    monthlyRevenue: "Revenu Mensuel Estimé",
    recentSystemLogs: "Événements Récents du Système",
    systemLogsTitle: "Journal d'Audit Système Complet",
    searchLogs: "Rechercher dans les logs...",
    userEmailCol: "Email Utilisateur",
    actionCol: "Action effectuée",
    detailsCol: "Détails du contexte",
    ipCol: "Adresse IP"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');

  // Load persisted language selection
  useEffect(() => {
    const savedLang = localStorage.getItem('aira_lang');
    if (savedLang && (savedLang === 'en' || savedLang === 'ar' || savedLang === 'fr')) {
      setLang(savedLang);
    }
  }, []);

  // Update layout direction dynamically
  useEffect(() => {
    localStorage.setItem('aira_lang', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
    document.body.className = lang === 'ar' ? 'lang-ar' : 'lang-en';
  }, [lang]);

  const t = (key) => {
    return translations[lang][key] || key;
  };

  const changeLanguage = (newLang) => {
    setLang(newLang);
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
